<!--Header-->
<?php
$wpUserData = wp_get_current_user();
$meta = B2S_Meta::getInstance();
$generalOptions = get_option('B2S_PLUGIN_GENERAL_OPTIONS');
$b2sActive = $meta->is_b2s_active();
$showYoast = ($_GET['page'] == 'blog2social-settings' && $meta->is_yoast_seo_active() && $b2sActive) ? 'block' : 'none';
$showAioseop = ($meta->is_aioseop_active() && $b2sActive) ? 'block' : 'none';
$showWebdaos = ($meta->is_webdados_active() && $b2sActive) ? 'block' : 'none';
?>

<div class="col-md-12 del-padding-left">
    <div class="col-md-9 del-padding-left">
        <!--Info System-->
        <?php if (version_compare(phpversion(), '5.5.3', '<')) { ?>
            <div class="panel panel-group">
                <div class="panel-body">
                    <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e("To use all features of Blog2Social, PHP version 5.5.3 or higher is required. Our support assists you as of PHP version 5.5.3. See also:", "blog2social"); ?>
                    <a target="_blank" href="<?php echo ((substr(B2S_LANGUAGE, 0, 2) == 'de' || (isset($_GET['lang']) && $_GET['lang'] == 'de')) ? 'https://www.blog2social.com/de/faq/content/1/63/de/systemvoraussetzungen-fuer-die-installation-von-blog2social.html' : 'https://www.blog2social.com/en/faq/content/1/58/en/system-requirements-for-installing-blog2social.html'); ?>"><?php _e('Technical requirements for Blog2Social', 'blog2social'); ?></a>         
                </div>
            </div>
        <?php } ?>

        <div class="panel panel-group b2s-network-auth-info b2s-mail-update-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Thank you. You\'ll now receive the blog updates from Blog2Social.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-heartbeat-fail" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('WordPress uses heartbeats by default, Blog2Social as well. Please enable heartbeats for using Blog2Social!', 'blog2social'); ?>
                <a target="_blank" href="<?php echo ((substr(B2S_LANGUAGE, 0, 2) == 'de' || (isset($_GET['lang']) && $_GET['lang'] == 'de')) ? 'https://www.blog2social.com/de/faq/content/1/63/de/systemvoraussetzungen-fuer-die-installation-von-blog2social.html' : 'https://www.blog2social.com/en/faq/content/1/58/en/system-requirements-for-installing-blog2social.html'); ?>"><?php _e('Please see FAQ', 'blog2social'); ?></a> 
            </div>
        </div>
        <div class="panel panel-group b2s-server-connection-fail" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('The connection to the server failed. Try again!', 'blog2social'); ?>
            </div>
        </div>

        <!--Info Meta Tags -->    
        <div class="panel panel-group b2s-clear-meta-tags b2s-clear-meta-tags-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('You have clear all page and post meta data successful.', 'blog2social'); ?>
            </div>
        </div> 
        <div class="panel panel-group b2s-clear-meta-tags b2s-clear-meta-tags-error" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('The page and post meta data could not be removed.', 'blog2social'); ?>
            </div>
        </div>  

        <div class="panel panel-group b2s-meta-tags-yoast b2s-meta-tags-success" style="display:<?php echo $showYoast; ?>;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('You have Yoast SEO active. Blog2Social Social Meta Tags overrides the meta tags from Yoast SEO.', 'blog2social'); ?>
            </div>
        </div> 

        <div class="panel panel-group b2s-meta-tags-aioseop b2s-meta-tags-danger" style="display:<?php echo $showAioseop; ?>;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('You currently have both Blog2Social Social Meta Tags and All in One SEO Pack plugins active. This is no recommended. Please, deactivated the All in One Seo Social Meta settings.', 'blog2social'); ?>
            </div>
        </div>  

        <div class="panel panel-group b2s-meta-tags-webdados b2s-meta-tags-danger" style="display:<?php echo $showWebdaos; ?>;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('You currently have both Blog2Social Social Meta Tags and Facebook Open Graph, Google+ and Twitter Card Tags plugins active. This is no recommended. Please, deactivated the Facebook Open Graph, Google+ and Twitter Card Tags settings.', 'blog2social'); ?>
            </div>
        </div>  

        <!--Info-Post-->
        <div class="panel panel-group b2s-network-auth-info b2s-post-remove-fail" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('This entry could not be removed. It\'s not yours!', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-post-remove-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('This entry was removed successful.', 'blog2social'); ?>
            </div>
        </div>
        <?php if (isset($_GET['origin']) && $_GET['origin'] == 'save_post' && isset($_GET['postStatus'])) { ?>
            <div class="panel panel-group b2s-network-auth-info">
                <div class="panel-body">
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span>
                    <?php
                    if ($_GET['postStatus'] == 'future') {
                        echo __('Post was scheduled successfully on your blog!', 'blog2social');
                    } else {
                        echo __('Post is published successfully on your blog!', 'blog2social');
                    }
                    ?>
                </div>
            </div>
        <?php } ?>

        <div class="b2s-trail-tracking" style="display: none;">
            <img height="1" width="1" style="border-style:none;" id="b2s-trail-tracking-src" alt="b2s-trail-tracking"/>
        </div>   
        <!--Info-Key-->
        <div class="panel panel-group b2s-key-area-success" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Version', 'blog2social'); ?> <span class="b2s-key-area-key-name"></span> <?php _e('is successfully activated.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-key-area-fail" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your entered License Key is invalid. Please contact support!', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-key-area-fail-max-use" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your license key has reached the maximum number of users.', 'blog2social'); ?>
            </div>
        </div>

        <!--Info-Network-->
        <div class="panel panel-group b2s-network-auth-info b2s-network-auth-success" style="display: none">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Your authorization was successful.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-network-add-mandant-success" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Your profile was saved successful.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-network-add-mandant-error" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your profile could not be saved.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-network-remove-fail" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your authorization could not be removed.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-network-remove-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Your authorization was removed successful.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-feedback-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Thank you! Your feedback has been received.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-feedback-fail" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your feedback could not be delivered.', 'blog2social'); ?>
            </div>
        </div>

        <!-- Info-Settings-->
        <div class="panel panel-group b2s-network-auth-info  b2s-settings-user-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Your settings were successfully saved.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info  b2s-settings-user-error" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your settings could not be saved.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-ship-settings-save" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Your settings were successfully saved.', 'blog2social'); ?>
            </div>
        </div>

        <!--Info-Trail-->
        <?php if (B2S_PLUGIN_USER_VERSION == 0 && !defined("B2S_PLUGIN_TRAIL_END")) { ?>
            <div class="panel panel-group b2s-trail-premium-info-area">
                <div class="panel-body">
                    <span class="glyphicon glyphicon-info-sign glyphicon-success"></span> <?php _e('Test Blog2Social PREMIUM 30 days for free', 'blog2social'); ?> <a data-toggle="modal" data-target="#b2s-trial-modal" href="#"><?php _e('Get Started', 'blog2social'); ?></a>
                </div>
            </div>
        <?php } ?>

        <?php if (defined("B2S_PLUGIN_TRAIL_END") && strtotime(B2S_PLUGIN_TRAIL_END) > strtotime(gmdate('Y-m-d H:i:s'))) { ?>
            <div class="panel panel-group b2s-trail-premium-info-area">
                <div class="panel-body">
                    <span class="glyphicon glyphicon-info-sign glyphicon-warning"></span>
                    <?php _e('Your Blog2Social Premium Free Version is activated for ', 'blog2social'); ?>
                    <?php
                    $days = B2S_Util::getTrialRemainingDays(B2S_PLUGIN_TRAIL_END, date_default_timezone_get());
                    echo $days > 0 ? ($days . __(' Days', 'blog2social')) : __(' today', 'blog2social');
                    ?>.
                    <a target="_blank" href="<?php echo B2S_Tools::getSupportLink('affiliate'); ?>"><?php _e('Upgrade to PREMIUM', 'blog2social'); ?></a>
                </div>
            </div>
        <?php } ?>

        <?php if (defined("B2S_PLUGIN_TRAIL_END") && strtotime(B2S_PLUGIN_TRAIL_END) < strtotime(gmdate('Y-m-d H:i:s'))) { ?>
            <div class="panel panel-group b2s-trail-premium-info-area">
                <div class="panel-body">
                    <span class="glyphicon glyphicon-info-sign glyphicon-success"></span> <?php _e('Your Blog2Social FREE-TRIAL Version has expired. Did you like this version?', 'blog2social'); ?>
                    <a target="_blank" class="btn btn-sm btn-link" href="<?php echo B2S_Tools::getSupportLink('affiliate'); ?>"><?php _e('Yes, I want more', 'blog2social'); ?></a>
                    <a href="#" class="btn btn-sm btn-link b2s-show-feedback-modal"><?php _e('No, I had enough', 'blog2social'); ?></a>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="col-md-3 del-padding-left hidden-xs hidden-sm">
        <?php
        $b2sLastVersion = get_option('b2s_plugin_version');
        if ($b2sLastVersion !== false) {
            echo '<span class="b2s-version-info pull-right">' . __('Version', 'blog2social') . ' ' . B2S_Util::getVersion($b2sLastVersion) . '</span>';
        }
        ?>
        <a target="_blank" href="https://www.blog2social.com">
            <img class="b2s-logo pull-right clear img-responsive" src="<?php echo plugins_url('/assets/images/b2s/b2s_logo.png', B2S_PLUGIN_FILE); ?>" alt="blog2social">
        </a>
    </div>
</div>
<div class="col-md-12 del-padding-left b2s-support-area hidden-md hidden-lg">
    <div class="col-md-9 del-padding-left">
        <a target="_blank" href="<?php echo B2S_Tools::getSupportLink('affiliate'); ?>" class="btn btn-success btn-block"><?php _e('Plans & Pricing', 'blog2social'); ?></a>
        <a target="_blank" href="<?php echo B2S_Tools::getSupportLink('faq'); ?>" class="btn btn-primary btn-block"> <?php _e('Support', 'blog2social'); ?></a>
    </div>
</div>
<!--Header-->


<!-- B2S-Trial -->
<div id="b2s-trial-modal" class="modal fade" role="dialog" aria-labelledby="b2s-trial-modal" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="b2s-modal-close close" data-modal-name="#b2s-trial-modal">&times;</button>
                <h4 class="modal-title"><?php _e('Test Blog2Social PREMIUM 30 days for free', 'blog2social'); ?></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="alert alert-danger b2s-trail-modal-fail" style="display:none;">
                            <?php _e('The free trial can not be started. This blog has been already registered for the free trial.', 'blog2social'); ?>
                        </div>
                        <div class="form-group col-xs-12">
                            <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Social Media Auto-Posting', 'blog2social'); ?><br>
                            <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Post on pages and groups', 'blog2social'); ?><br>
                            <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Share on multiple accounts per network', 'blog2social'); ?><br>
                            <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Best Time Scheduler: Schedule once, multiple times or recurringly.', 'blog2social'); ?><br>  
                            <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Reporting with links to all published social media posts', 'blog2social'); ?><br>  
                        </div>
                        <div class="form-group col-xs-12">
                            <label for="trial_email"><?php _e('E-Mail', 'blog2social'); ?></label>
                            <input id="trial_email" class="form-control" type="email" value="<?php echo $wpUserData->user_email; ?>" name="trial_email">
                        </div>
                        <div class="form-group col-xs-12  col-md-6">
                            <label for="trial_vorname"><?php _e('First Name', 'blog2social'); ?></label>
                            <input id="trial_vorname" class="form-control" type="text" value="<?php echo $wpUserData->user_firstname; ?>" name="trial_vorname">
                        </div>
                        <div class="form-group col-xs-12  col-md-6">
                            <label for="trial_nachname"><?php _e('Last Name', 'blog2social'); ?></label>
                            <input id="trial_nachname" class="form-control" type="text" value="<?php echo $wpUserData->user_lastname; ?>" name="trial_nachname">
                        </div>
                        <div class="col-xs-12">
                            <div class="pull-left">
                                <span class="glyphicon glyphicon-info-sign glyphicon-primary"></span>  <?php _e('No credit card required', 'blog2social'); ?>
                            </div>
                            <div class="pull-right">
                                <input type="hidden" name="trial_url" id="trial_url" value="<?php echo get_option('home'); ?>" />
                                <input class="btn btn-success pull-right b2s-trail-btn-start" type="submit" value="<?php _e('Get Started', 'blog2social'); ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

